# LISTAS

In [ ]:
mi_lista = [1,2,3,4,5,6.1, 'Hello world']
mi_lista

In [2]:
#Iterar una lista
for contenido in mi_lista:
    print(contenido)
print('fin')

1
2
3
4
5
6.1
Hello world
fin


In [3]:
#acceder a un elemento de la lista
print(mi_lista[6])

Hello world


In [4]:
# Modificar elemento en una lista
mi_lista[6] = "Bienvenido al curso"
print(mi_lista)

[1, 2, 3, 4, 5, 6.1, 'Bienvenido al curso']


In [5]:
# Eliminar un elemento en la lista
mi_lista.remove("Bienvenido al curso")
print(mi_lista)

[1, 2, 3, 4, 5, 6.1]


In [6]:
# €liminar elemento por indice
mi_lista.pop(2)
print(mi_lista)

[1, 2, 4, 5, 6.1]


In [7]:
# Visualizar la lista
mi_lista

[1, 2, 4, 5, 6.1]

In [8]:
# Agregar elementos al final de la lista
mi_lista.append(7)

In [9]:
mi_lista

[1, 2, 4, 5, 6.1, 7]

In [10]:
# Agregar un elemento en cualquier indice de la lista
mi_lista.insert(2, 3)
print(mi_lista)

[1, 2, 3, 4, 5, 6.1, 7]


# TUPLAS

In [12]:
tupla_1 = (1,2,3,4)
tupla_2 = (5,6,7,8)

In [13]:
# Operaciones con tuplas: conjunto estático
tupla_1 + tupla_2


(1, 2, 3, 4, 5, 6, 7, 8)

# SETS

In [14]:
# no importa el orden y son valores NO repetidos
set_1 = {'k', 'a', 'b,', 'c', 'k'}

In [15]:
print(set_1)

{'k', 'c', 'a', 'b,'}


In [16]:
# Agregar
set_1.add('z')
print(set_1)

{'k', 'b,', 'c', 'z', 'a'}


# DICCIONARIOS

In [17]:
mi_diccionario = {'elemento_1': 100, 
                 'elemento_2': 200}
mi_diccionario

{'elemento_1': 100, 'elemento_2': 200}

In [18]:
# Acceder mediante elementos llaves
print(mi_diccionario['elemento_2'])

200


In [19]:
# Agregar
mi_diccionario['elemento_3'] = 300
print(mi_diccionario)

{'elemento_1': 100, 'elemento_2': 200, 'elemento_3': 300}


In [20]:
# Eliminar un elemento
del mi_diccionario['elemento_3']
print(mi_diccionario)

{'elemento_1': 100, 'elemento_2': 200}


In [21]:
# Accediendo a llaves
print(mi_diccionario.keys())

dict_keys(['elemento_1', 'elemento_2'])


In [22]:
# Accediendo a valores
print(mi_diccionario.values())

dict_values([100, 200])


# CONDICIONALES

In [23]:
# Condicional simple
variable = 13

if variable > 12:
    print('Es mayor!! :D')
    

Es mayor!! :D


In [25]:
# Condicional doble
variable = 11

if variable > 12:
    print('Es mayor!! :D')
else:
    print('No es mayor!! D:')

No es mayor!! D:


In [26]:
# Condicional compuesta
variable_1 = 1
variable_2 = 2

if variable_1 == 1 and variable_2 == 2:
    print('Las variables son consecutivas ascendentes')
else:
    print('Las variables NO son consecutivas ascendentes')

Las variables son consecutivas ascendentes


# CICLOS

In [27]:
# Ciclo for
for contador in range(0,10):
    print(contador)

0
1
2
3
4
5
6
7
8
9


In [28]:
# Ciclo while
variable = 0

while variable < 10:
    print(variable)
    variable = variable + 1

0
1
2
3
4
5
6
7
8
9


# Importación de librerías

In [29]:
import numpy as np # operaciones
import pandas as pd #
import seaborn as sns #

# numpy

In [30]:
# declarar matriz de 15 elementos de 5 columnas 3 renglones
a = np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [31]:
type(a)

numpy.ndarray

In [32]:
a.shape #forma del objeto

(3, 5)

In [33]:
a.dtype.name #tipo de dato

'int64'

In [34]:
a.size # num de elementos dentro del objeto

15

In [35]:
#listas numpy
a = np.array([2,3,4])

In [36]:
# operaciones básicas numpy
lista_np_1 = np.array([1,2,3])
lista_np_2 = np.array([4,5,6])

print(lista_np_1 + lista_np_2)
print(lista_np_1 * lista_np_2)
print(lista_np_1 / lista_np_2)

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]


# pandas

In [ ]:
frame_datos = pd.read_csv('.//DATOS_COVID19_MEXICO_reducido.csv', encoding='latin-1')
frame_datos

In [ ]:
# Visualizar solo 5 elementos
frame_datos.head()

In [ ]:
# Visualizar n elementos
frame_datos.head(10)

In [ ]:
# Visualizar el final
frame_datos.tail(10)

In [ ]:
# Inspeccionamos tipos de datos
frame_datos.info()

In [ ]:
# Inspeccionamos valores null: conteo de null por columnas
frame_datos.isna().sum()

In [ ]:
# Summary (cuartiles en porcenyaje)
frame_datos.describe()

In [ ]:
#histplot
sns.distplot(frame_datos['SEXO'], kde =False)

In [37]:
#Funciones en Python

def multiplica_nums(n_1, n_2):
    return n_1 * n_2
print(multiplica_nums(3,4))

12


In [39]:
# Funciones lambdas
multiplica_lamdas = lambda n_1, n_2 : n_1 * n_2
print (multiplica_lamdas(3,4))

12
